package receiver

import (
	_ "embed"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"sync"
)

// keydb.json is generated by tools/ubxkeydb from the u-blox interface
// descriptions (HPG 2.00 first, then later X20 releases), with pyubx2 filling
// in names the X20 documents omit. A key missing from it is shown as
// undocumented; its name is never inferred from neighbouring IDs.
//
//go:embed keydb.json
var keydbJSON []byte

// EnumValue is one documented constant of an E-type key.
type EnumValue struct {
	Name  string `json:"name"`
	Value int64  `json:"value"`
	Desc  string `json:"desc"`
}

// KeyInfo describes a configuration key as documented by u-blox.
type KeyInfo struct {
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	Scale  string      `json:"scale,omitempty"`
	Unit   string      `json:"unit,omitempty"`
	Desc   string      `json:"desc,omitempty"`
	Source string      `json:"source"`
	Enum   []EnumValue `json:"enum,omitempty"`
}

var (
	keydbOnce sync.Once
	keydb     map[uint32]KeyInfo
)

func loadKeyDB() {
	raw := map[string]KeyInfo{}
	if err := json.Unmarshal(keydbJSON, &raw); err != nil {
		panic("receiver: embedded keydb.json is invalid: " + err.Error())
	}
	keydb = make(map[uint32]KeyInfo, len(raw))
	for k, v := range raw {
		n, err := strconv.ParseUint(k, 16, 32)
		if err != nil {
			panic("receiver: bad key in keydb.json: " + k)
		}
		keydb[uint32(n)] = v
	}
}

// LookupKey returns the documented description of a configuration key.
func LookupKey(key uint32) (KeyInfo, bool) {
	keydbOnce.Do(loadKeyDB)
	v, ok := keydb[key]
	return v, ok
}

// KeyName returns the documented name, or "" for an undocumented key.
func KeyName(key uint32) string {
	v, _ := LookupKey(key)
	return v.Name
}

// decodeInt interprets a little-endian value according to the documented type.
func decodeInt(typ string, raw []byte) (int64, bool) {
	var u uint64
	switch len(raw) {
	case 1:
		u = uint64(raw[0])
	case 2:
		u = uint64(binary.LittleEndian.Uint16(raw))
	case 4:
		u = uint64(binary.LittleEndian.Uint32(raw))
	case 8:
		u = binary.LittleEndian.Uint64(raw)
	default:
		return 0, false
	}
	if strings.HasPrefix(typ, "I") {
		shift := 64 - 8*uint(len(raw))
		return int64(u<<shift) >> shift, true
	}
	return int64(u), true
}

// DisplayValue renders a raw value for people: booleans, enum constant names,
// signed integers and floats, with the documented scale and unit.
func DisplayValue(key uint32, raw []byte) string {
	info, ok := LookupKey(key)
	if !ok || KeySize(key) != len(raw) {
		return hex.EncodeToString(raw)
	}
	switch t := info.Type; {
	case t == "L":
		if len(raw) == 1 && raw[0] == 1 {
			return "true"
		}
		if len(raw) == 1 && raw[0] == 0 {
			return "false"
		}
		return hex.EncodeToString(raw)
	case t == "R4" && len(raw) == 4:
		return withUnit(strconv.FormatFloat(float64(math.Float32frombits(binary.LittleEndian.Uint32(raw))), 'g', -1, 32), info)
	case t == "R8" && len(raw) == 8:
		return withUnit(strconv.FormatFloat(math.Float64frombits(binary.LittleEndian.Uint64(raw)), 'g', -1, 64), info)
	case strings.HasPrefix(t, "X"):
		return "0x" + strings.ToUpper(hexLE(raw))
	case strings.HasPrefix(t, "E"):
		n, _ := decodeInt(t, raw)
		for _, e := range info.Enum {
			if e.Value == n {
				return fmt.Sprintf("%s (%d)", e.Name, n)
			}
		}
		return strconv.FormatInt(n, 10)
	case strings.HasPrefix(t, "U"), strings.HasPrefix(t, "I"):
		n, ok := decodeInt(t, raw)
		if !ok {
			return hex.EncodeToString(raw)
		}
		s := strconv.FormatInt(n, 10)
		if sc, err := strconv.ParseFloat(info.Scale, 64); err == nil && sc != 1 {
			s += " × " + info.Scale
		}
		return withUnit(s, info)
	}
	return hex.EncodeToString(raw)
}

func withUnit(s string, info KeyInfo) string {
	if info.Unit != "" {
		return s + " " + info.Unit
	}
	return s
}

// hexLE prints a little-endian bitfield most-significant byte first.
func hexLE(raw []byte) string {
	b := make([]byte, len(raw))
	for i := range raw {
		b[len(raw)-1-i] = raw[i]
	}
	return hex.EncodeToString(b)
}

// ParseValue converts operator input into the raw value for key. It accepts
// true/false for L keys, a documented constant name or a number for E keys,
// and a number in unscaled key units otherwise. For undocumented keys and as a
// universal escape hatch, "hex:<bytes>" supplies the little-endian bytes.
func ParseValue(key uint32, text string) ([]byte, error) {
	text = strings.TrimSpace(text)
	size := KeySize(key)
	if size == 0 {
		return nil, fmt.Errorf("key 0x%08X has no valid size", key)
	}
	if h, ok := strings.CutPrefix(text, "hex:"); ok {
		b, err := hex.DecodeString(strings.ReplaceAll(h, " ", ""))
		if err != nil || len(b) != size {
			return nil, fmt.Errorf("key 0x%08X needs %d hex bytes", key, size)
		}
		return b, nil
	}
	info, ok := LookupKey(key)
	if !ok {
		return nil, fmt.Errorf("key 0x%08X is undocumented; supply hex:<bytes>", key)
	}
	out := make([]byte, size)
	switch t := info.Type; {
	case t == "L":
		switch strings.ToLower(text) {
		case "true", "1", "on", "enabled":
			out[0] = 1
		case "false", "0", "off", "disabled":
		default:
			return nil, fmt.Errorf("%s is a boolean: use true or false", info.Name)
		}
		return out, nil
	case t == "R4" || t == "R8":
		f, err := strconv.ParseFloat(text, 64)
		if err != nil {
			return nil, fmt.Errorf("%s needs a number", info.Name)
		}
		if size == 4 {
			binary.LittleEndian.PutUint32(out, math.Float32bits(float32(f)))
		} else {
			binary.LittleEndian.PutUint64(out, math.Float64bits(f))
		}
		return out, nil
	case strings.HasPrefix(t, "E"):
		for _, e := range info.Enum {
			if strings.EqualFold(e.Name, text) {
				text = strconv.FormatInt(e.Value, 10)
				break
			}
		}
	}
	signed := strings.HasPrefix(info.Type, "I")
	var u uint64
	if signed {
		n, err := strconv.ParseInt(text, 0, 8*size)
		if err != nil {
			return nil, fmt.Errorf("%s needs a signed %d-bit integer", info.Name, 8*size)
		}
		u = uint64(n)
	} else {
		n, err := strconv.ParseUint(text, 0, 8*size)
		if err != nil {
			return nil, fmt.Errorf("%s needs an unsigned %d-bit integer", info.Name, 8*size)
		}
		u = n
	}
	for i := 0; i < size; i++ {
		out[i] = byte(u >> (8 * i))
	}
	return out, nil
}

// MessagePorts are the ports an X20 CFG-MSGOUT key can address.
var MessagePorts = []string{"USB", "UART1", "UART2", "I2C", "SPI"}

// PortRate is one CFG-MSGOUT key: a message's rate on one port.
type PortRate struct {
	Key  string `json:"key"`
	Rate int    `json:"rate"`
}

// MessageOutput is one output message and its rate on each port. A rate is
// the number of navigation epochs between outputs; 0 disables the message.
type MessageOutput struct {
	ID       string              `json:"id"`       // key stem, e.g. RTCM_3X_TYPE1077
	Protocol string              `json:"protocol"` // UBX, RTCM, NMEA, PUBX
	Label    string              `json:"label"`    // e.g. RTCM 1077, UBX NAV-SAT
	Ports    map[string]PortRate `json:"ports"`
}

// MessageOutputs groups documented CFG-MSGOUT keys by message.
func MessageOutputs(kv map[uint32][]byte) []MessageOutput {
	by := map[string]*MessageOutput{}
	for k, v := range kv {
		name := KeyName(k)
		stem, ok := strings.CutPrefix(name, "CFG-MSGOUT-")
		if !ok || len(v) != 1 {
			continue
		}
		i := strings.LastIndex(stem, "_")
		if i < 0 {
			continue
		}
		id, port := stem[:i], stem[i+1:]
		if !validPort(port) {
			continue
		}
		m := by[id]
		if m == nil {
			proto, label := messageLabel(id)
			m = &MessageOutput{ID: id, Protocol: proto, Label: label, Ports: map[string]PortRate{}}
			by[id] = m
		}
		m.Ports[port] = PortRate{Key: fmt.Sprintf("0x%08X", k), Rate: int(v[0])}
	}
	out := make([]MessageOutput, 0, len(by))
	for _, m := range by {
		out = append(out, *m)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Protocol != out[j].Protocol {
			return out[i].Protocol < out[j].Protocol
		}
		return out[i].Label < out[j].Label
	})
	return out
}

func validPort(p string) bool {
	for _, x := range MessagePorts {
		if x == p {
			return true
		}
	}
	return false
}

func messageLabel(id string) (string, string) {
	switch {
	case strings.HasPrefix(id, "RTCM_3X_TYPE"):
		return "RTCM", "RTCM " + strings.TrimPrefix(id, "RTCM_3X_TYPE")
	case strings.HasPrefix(id, "RTCM_"):
		return "RTCM", "RTCM " + strings.ReplaceAll(strings.TrimPrefix(id, "RTCM_"), "_", "-")
	case strings.HasPrefix(id, "UBX_"):
		return "UBX", "UBX " + strings.ReplaceAll(strings.TrimPrefix(id, "UBX_"), "_", "-")
	case strings.HasPrefix(id, "NMEA_ID_"):
		return "NMEA", "NMEA " + strings.TrimPrefix(id, "NMEA_ID_")
	case strings.HasPrefix(id, "NMEA_"):
		return "NMEA", "NMEA " + strings.ReplaceAll(strings.TrimPrefix(id, "NMEA_"), "_", "-")
	case strings.HasPrefix(id, "PUBX_ID_"):
		return "PUBX", "PUBX " + strings.TrimPrefix(id, "PUBX_ID_")
	}
	p, _, _ := strings.Cut(id, "_")
	return p, strings.ReplaceAll(id, "_", " ")
}

// Signal is one CFG-SIGNAL enable key.
type Signal struct {
	Key     string `json:"key"`
	Name    string `json:"name"`
	Label   string `json:"label"`
	Enabled bool   `json:"enabled"`
}

// Constellation is a GNSS enable key with its per-signal keys.
type Constellation struct {
	ID        string   `json:"id"` // GPS, GAL, BDS, ...
	Key       string   `json:"key"`
	Label     string   `json:"label"`
	Enabled   bool     `json:"enabled"`
	Supported bool     `json:"supported"` // listed by MON-VER for this firmware
	Signals   []Signal `json:"signals"`
}

// monVerNames maps CFG-SIGNAL constellation prefixes to MON-VER spellings.
var monVerNames = map[string]string{"GPS": "GPS", "GAL": "GAL", "BDS": "BDS",
	"GLO": "GLO", "QZSS": "QZSS", "SBAS": "SBAS", "NAVIC": "NAVIC"}

// Constellations groups documented CFG-SIGNAL enable keys by system. supported
// is the MON-VER constellation list; a system absent from it is flagged
// rather than hidden, because the firmware still accepts its keys.
func Constellations(kv map[uint32][]byte, supported []string) []Constellation {
	sup := map[string]bool{}
	for _, s := range supported {
		sup[s] = true
	}
	by := map[string]*Constellation{}
	get := func(id string) *Constellation {
		c := by[id]
		if c == nil {
			c = &Constellation{ID: id, Supported: sup[monVerNames[id]]}
			by[id] = c
		}
		return c
	}
	for k, v := range kv {
		info, ok := LookupKey(k)
		stem, isSig := strings.CutPrefix(info.Name, "CFG-SIGNAL-")
		if !ok || !isSig || info.Type != "L" || len(v) != 1 {
			continue
		}
		stem, isEna := strings.CutSuffix(stem, "_ENA")
		if !isEna {
			continue
		}
		sys, sig, hasSig := strings.Cut(stem, "_")
		if _, known := monVerNames[sys]; !known {
			continue
		}
		c := get(sys)
		key := fmt.Sprintf("0x%08X", k)
		if !hasSig {
			c.Key, c.Label, c.Enabled = key, strings.TrimSuffix(info.Desc, " enable"), v[0] == 1
			if strings.EqualFold(info.Desc, "BeiDou Enable") {
				c.Label = "BeiDou"
			}
			continue
		}
		c.Signals = append(c.Signals, Signal{Key: key, Name: sig, Label: info.Desc, Enabled: v[0] == 1})
	}
	order := map[string]int{"GPS": 0, "GAL": 1, "BDS": 2, "GLO": 3, "QZSS": 4, "SBAS": 5, "NAVIC": 6}
	out := make([]Constellation, 0, len(by))
	for _, c := range by {
		if c.Key == "" {
			continue
		}
		sort.Slice(c.Signals, func(i, j int) bool { return c.Signals[i].Key < c.Signals[j].Key })
		out = append(out, *c)
	}
	sort.Slice(out, func(i, j int) bool { return order[out[i].ID] < order[out[j].ID] })
	return out
}
